version: '3.2'
services:
  db:
    image: mysql:5.7
    container_name: appsDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: themagicword

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
    PMA_HOST: db